const committeeData = {
    organising: [
        {
            title: 'Chief Patron',
            members: [
                { name: 'Dr Rajeev Ranjan Vederah', img: './dummy.jpg', position: 'Chancellor, Thapar Institute of Engineering and Technology, Patiala, India' },
            ],
        },
        {
            title: 'Patron',
            members: [
                { name: 'Prof Padmakumar Nair', img: './dummy.jpg', position: 'Vice Chancellor, Thapar Institute of Engineering and Technology, Patiala, India' },
            ],
        },
        {
            title: 'Honorary Chairs',
            members: [
                { name: 'Prof Ajay Batish', img: './dummy.jpg', position: 'Pro Vice Chancellor, Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Prof Hans Van Ees', img: './dummy.jpg', position: 'Honorary Dean, Thapar School of Liberal Arts & Sciences, Patiala.' },
            ],
        },
        {
            title: 'General Chairs',
            members: [
                { name: 'Prof Vinay Kumar', img: './dummy.jpg', position: 'Thapar School of Liberal Arts & Sciences, Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Prof Tim Miller', img: './dummy.jpg', position: 'School of Electrical Engineering and Computer Science, The University of Queensland' },
            ],
        },
        {
            title: 'Organising Chairs',
            members: [
                { name: 'Dr Rahul Upadhyay', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Mohammed Usman', img: './dummy.jpg', position: 'Bennett University, Noida, India' },
            ],
        },
        {
            title: 'Organizing Secretary',
            members: [
                { name: 'Dr Shashikant', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
            ],
        },
        {
            title: 'Steering Committee',
            members: [
                { name: 'Prof R S Kaler', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Prof Meenakshi Sood', img: './dummy.jpg', position: 'National Institute of Technical Teachers Training and Research, Chandigarh, India' },
                { name: 'Prof Shalini Batra', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Prof Sunil Bhooshan', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Shri Ram', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Ashutosh Kumar Singh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Prof Fernando Díaz de María', img: './dummy.jpg', position: 'Departamento de Teoría de la Señal y Comunicaciones, Universidad Carlos III de Madrid, Spain' },

            ],
        },
        {
            title: 'Advisory Committee',
            members: [
                { name: 'Prof Rajesh Dikshit', img: './dummy.jpg', position: 'National Institute of Technical Teachers Training and Research, Bhopal, India' },
                { name: 'Prof Omar Farooq', img: './dummy.jpg', position: 'Aligarh Muslim University, Patiala, India' },
                { name: 'Prof. Kulbir Singh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Prof Sandeep Sharma', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Prof Dwarka Nath Rath', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Prof Hem Dutt Joshi', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Prof Saurabh Bhardwaj', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Prof Rajashri Khanai', img: './dummy.jpg', position: 'KLE Technological University, Belagavi Campus, India' },

                { name: 'Dr. Sara Chandy', img: './dummy.jpg', position: 'Technical Director, Associated Medical Specialities, Vellore' },
                { name: 'Dr Karun Verma', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },

                { name: 'Dr Mudit Gupta', img: './dummy.jpg', position: 'Saral Diagnostics, Delhi, India' },

                { name: 'Rubén Solera Ureña', img: './dummy.jpg', position: 'Instituto de Engenharia de Sistemas e Computadores - Investigação e Desenvolvimento, Lisbon, Portugal' },

            ],
        },
    ],
    supporting: [
        {
            title: 'Finance Committee',
            members: [
                { name: 'Sh. Pankaj Sinha', img: './dummy.jpg', position: 'Chair: Finance Officer, Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Shashikant', img: './dummy.jpg', position: 'Member: Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Arun Chatterjee', img: './dummy.jpg', position: 'Member: Thapar Institute of Engineering and Technology, Patiala, India' },
            ],
        },
        {
            title: 'Publications Chairs',
            members: [
                { name: 'Dr Mohd Wajid', img: './dummy.jpg', position: 'Aligarh Muslim University, Aligarh' },
                { name: 'Dr Vivek Bawa', img: './dummy.jpg', position: 'University of Plymouth, UK' },
                { name: 'Dr. Chandramohan Dhasarathan', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
            ],
        },
        {
            title: 'Sponsorship and Industry Liaison Committee',
            members: [
                { name: 'Dr Anupam Garg', img: './dummy.jpg', position: 'Thapar School of Liberal Arts & Sciences, Patiala, India' },
                { name: 'Dr Gaganpreet Kaur', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Alka Pandita', img: './dummy.jpg', position: 'Thapar School of Liberal Arts & Sciences, Patiala, India' },
                { name: 'Mr Munish Prabhakar', img: './dummy.jpg', position: 'Thapar School of Liberal Arts & Sciences, Patiala, India' },
            ],
        },
        {
            title: 'Publicity Committee',
            members: [
                { name: 'Ms Nivedita Anand', img: './dummy.jpg', position: 'Thapar School of Liberal Arts & Sciences, Patiala, India' },
                { name: 'Ms Radhika Kalia', img: './dummy.jpg', position: 'Thapar School of Liberal Arts & Sciences, Patiala, India' },

                { name: 'Ms. Navtika Bedi', img: './dummy.jpg', position: 'Thapar School of Liberal Arts & Sciences, Patiala, India' },
                { name: 'Mr Arnab Rath', img: './dummy.jpg', position: 'Thapar School of Liberal Arts & Sciences, Patiala, India' },
            ],
        },
        {
            title: 'Registration Committee',
            members: [
                { name: 'Dr Arun Chatterjee', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Gaganpreet Kaur', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Gitanjali Chandwani', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Rajneesh Sharma', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Sheikh Adil Edrisi', img: './dummy.jpg', position: 'Thapar School of Liberal Arts and Sciences, Patiala, India' },
            ],
        },
        {
            title: 'Local Arrangement Committee',
            members: [
                { name: 'Dr Anil Arora', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Ms Riya Kalia', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Ms Palack Deep Kaur', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Mr Harvinder', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Mr Manoj Arya', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
            ],
        },
    ],
    sectionOversight: [
        {
            title: 'Section Oversight Committee',
            members: [
                { name: 'Prof. Vivek Shrivastava', img: './dummy.jpg', position: 'Lead Member Coordinator for AIDL-HCSY and Section Executive Committee Member Co-opted &Member-IEEE Delhi Section STDCOM on T & P Act' },
                { name: 'Prof. Rajnish Sharma', img: './dummy.jpg', position: 'Section Vice Chair & Member-IEEE Delhi Section STDCOM on T & P Act' },
                { name: 'Dr. Ekta Gandotra', img: './dummy.jpg', position: 'Member-IEEE Delhi Section STDCOM on T & P Act' },
                { name: 'Prof. Sneha Kabra', img: './dummy.jpg', position: 'Section Secretary, Interim Section Treasurer & Member-IEEE Delhi Section STDCOM on T & P Act' },
            ],
        },
    ],
    technical: [
        {
            title: 'Technical Program Committee Members',
            members: [
                { name: 'Dr. M Waris Abdullah', img: './dummy.jpg', position: 'Qualcomm, Cambridge, United Kingdom' },
                { name: 'Dr. Ankush Kansal', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Abhishek Srivastava', img: './dummy.jpg', position: 'Indian Institute of Technology Bombay, India' },
                { name: 'Dr. Hardeep Singh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Hemant Kumar Meena', img: './dummy.jpg', position: 'Malaviya National Institute of Technology Jaipur, India' },
                { name: 'Dr. Sanjay Kumar', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Sujay Deb', img: './dummy.jpg', position: 'Washington State University, United States of America' },
                { name: 'Dr. Ashutosh Kumar Singh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Kishor P. Sarawadekar', img: './dummy.jpg', position: 'Indian Institute of Technology (Banaras Hindu University) Varanasi, India' },
                { name: 'Dr. Surbhi Sharma', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Sumit J Darak', img: './dummy.jpg', position: 'Nanyang Technological University, Singapore' },
                { name: 'Dr. Ravi Kumar', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Mohsin Jamali', img: './dummy.jpg', position: 'University of Toledo, United States of America' },
                { name: 'Dr. Sujit Kumar Patel', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Vijayalakshmi Ahanathapillai', img: './dummy.jpg', position: 'University of Warwick, United Kingdom' },
                { name: 'Dr. Debabrata Ghosh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Zeeshan Ahmad', img: './dummy.jpg', position: 'University of Wolverhampton, United Kingdom' },
                { name: 'Dr. Amit Munjal', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Rohan Katti', img: './dummy.jpg', position: 'Bennett University, Greater Noida, India' },
                { name: 'Dr. Bharat Garg', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Ankit Pandey', img: './dummy.jpg', position: 'Bennett University, Greater Noida, India' },
                { name: 'Dr. Rajneesh Sharma', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Mohammed Wasid', img: './dummy.jpg', position: 'The LNM Institute of Information Technology, Jaipur, India' },
                { name: 'Dr. Durgesh Singh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Ajay Yadav', img: './dummy.jpg', position: 'Bennett University, Greater Noida, India' },
                { name: 'Dr. Arnab Pattanayak', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Sivaram Nishal Ramadas', img: './dummy.jpg', position: 'Birmingham City University, United Kingdom' },
                { name: 'Dr. Shireesh Kumar Rai', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Simarjit Kaur', img: './dummy.jpg', position: 'Chitkara University, Rajpura, India' },
                { name: 'Dr. Sandeep Mandia', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Rohit Rana', img: './dummy.jpg', position: 'LNM Institute of Engineering and Technology, Jaipur, India' },
                { name: 'Dr. Mahesh Shamrao Chaudhari', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Vishal Pandey', img: './dummy.jpg', position: 'University of Engineering and Management Jaipur, India' },
                { name: 'Dr. Deepak Kumar Rakesh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Akash Gupta', img: './dummy.jpg', position: 'LNM Institute of Engineering and Technology, Jaipur, India' },
                { name: 'Dr. Sumit Varshaney', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Shishir Maheshwari', img: './dummy.jpg', position: 'Motilal Nehru National Institute of Technology Allahabad, India' },
                { name: 'Dr. Chandramohan Dhasarathan', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Shalabh Kumar Mishra', img: './dummy.jpg', position: 'Madan Mohan Malaviya University of Technology, Gorakhpur, India' },
                { name: 'Dr. Ashu Sharma', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Geetaly', img: './dummy.jpg', position: 'Plaksha University, Chandigarh, India' },
                { name: 'Dr. Amanpreet Kaur-II', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Parveen Malik', img: './dummy.jpg', position: 'National Institute of Technology Kurukshetra, India' },
                { name: 'Dr. Geetika Dua', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Saurabh Kumar', img: './dummy.jpg', position: 'National Institute of Technology Hamirpur, India' },
                { name: 'Dr. Dinesh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Dharmendra Yadav', img: './dummy.jpg', position: 'National Institute of Technology Kurukshetra, India' },
                { name: 'Dr. Poonam Verma', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Shatrugan Modi', img: './dummy.jpg', position: 'Indian Institute of Information Technology Una, India' },
                { name: 'Dr. Debayani Ghosh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Anshu Parashar', img: './dummy.jpg', position: 'National Institute of Technology Kurukshetra, India' },
                { name: 'Dr. Saurabh Sharma', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Amrita', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Mona Agarwal', img: './dummy.jpg', position: 'The NorthCap University, Gurugram, India' },
                { name: 'Dr. Husanbir Singh Pannu', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Chinmaya Panigrahy', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Manan Jani', img: './dummy.jpg', position: 'Northern India Engineering College, New Delhi, India' },
                { name: 'Dr. Anu Bajaj', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Anjula Mehto', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Manvir Kaur', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Tanvi Dovedi', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Neeraj Grover', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Riyaz Ahmad', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Aarti Bansal', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. S Pratap Singh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Mohammad Faseehuddin', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Ankit Soni', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Shruti Arora', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Nitin Arora', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Raja Rout', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Pankaj Kumar', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Shivendra Shivani', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Nidhi Kalra', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. P Kalyan Chakravarthy K', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Sachin Singh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Gautam Setia', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Ashutosh Aggarwal', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Vishal Gupta', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Manpreet Singh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Danie Roy A. B', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Deepshikha Tiwari', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Jasmeet Singh', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Rohit Ahuja', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Shailendra Tiwari', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Lateef Ahmad Wani', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Munish Kansal', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Vikas Sharma', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Kavita', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Priyankar Dey', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Manjeet Singh', img: './dummy.jpg', position: 'National Institute of Technology, Jalandhar' },
                { name: 'Dr. Nitesh Kashyap', img: './dummy.jpg', position: 'National Institute of Technology, Jalandhar' },
                { name: 'Dr. Shishir Maheshwari', img: './dummy.jpg', position: 'Motilal Nehru National Institute of Technology Allahabad, India' },
                { name: 'Dr. Sukwinder Singh', img: './dummy.jpg', position: 'DR B R AMBEDKAR NATIONAL INSTITUTE OF TECHNOLOGY JALANDHAR, PUNJAB (INDIA)' },
                { name: 'Dr. Anil Arora', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Gitanjali Chandwani Manocha', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Gaganpreet Kaur', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr Arun Chatterjee', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Rajneesh Sharma', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Anupam Garg', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Bharat Verma', img: './dummy.jpg', position: 'The LNM Institute of Information Technology' },
                { name: 'Aviral Chharia', img: './dummy.jpg', position: 'Carnegie Mellon University, USA' },
                { name: 'Dr. Sachin Kansal', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Harleen Kaur', img: './dummy.jpg', position: 'Thapar Institute of Engineering and Technology, Patiala, India' },
                { name: 'Dr. Kirtiman Singh', img: './dummy.jpg', position: 'UPES, Dehradun' },
                { name: 'Dr. Neeraj Kumar Goswami', img: './dummy.jpg', position: 'Banasthali Vidyapith, Rajasthan' },
                { name: 'Dr. Gurpreet Kaur', img: './dummy.jpg', position: 'IIIT, Una' },
                { name: 'Dr. Tanu Wadhera', img: './dummy.jpg', position: 'IIIT, Una' },
            ],
        },
    ]
};

export default committeeData;